---
- hosts: localhost
  user: ryanhanks
  connection: local

  roles:
    - roderik.superlumic-osx-defaults

  vars:
    - use_zsh: true
    - git_user_name: "Ryan Hanks"
    - git_user_email: ryan.hanks@workiva.com
    - osx_defaults:
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'minimize-to-application'
        type: integer
        value: 1
      - domain: 'NSGlobalDomain'
        key: 'AppleKeyboardUIMode'
        type: integer
        value: 3
      - domain: 'NSGlobalDomain'
        key: 'KeyRepeat'
        type: integer
        value: 0
      - domain: 'NSGlobalDomain'
        key: 'InitialKeyRepeat'
        type: integer
        value: 15
      - domain: 'NSGlobalDomain'
        key: 'com.apple.trackpad.scaling'
        type: integer
        value: 3

  tasks:
    - stat: path="/Volumes/VMware Shared Folders/Data"
      register: vmware_shared_folder_data
    - name: create symlink to VMware Share Folders/Data if we're in a VM
      file: dest=/Volumes/Data src="/Volumes/VMware Shared Folders/Data" state=link
      when: vmware_shared_folder_data.stat.exists and vmware_shared_folder_data.stat.isdir
    - name: ignore images
      become: yes
      become_method: sudo
      copy:
        src: files/fstab
        dest: /etc/fstab
    - name: Installing zsh package
      homebrew:
        name: "{{ item }}"
        state: present
      with_items:
        - zsh

    - name: Setting default shell
      shell: "chsh -s $(which zsh) {{ ansible_ssh_user }}"
      sudo: True
      when: use_zsh

    - name: add to sudoers without password
      become: yes
      become_method: sudo
      lineinfile: >
        dest=/etc/sudoers
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state=present
        create=true
      with_items:
        - { regexp: '^ryanhanks', line: 'ryanhanks ALL=(ALL) NOPASSWD: ALL' }
    - name: set never sleep
      become: yes
      become_method: sudo
      shell: pmset  -a sleep 0
    - name: clone dotfiles
      git:
        repo: git@github.com:ryanhanks-wf/dotfiles
        dest: ~/src/github.com/ryanhanks-wf/dotfiles
        update: no
    - name: link dotfiles
      file: src=~/src/github.com/ryanhanks-wf/dotfiles dest=~/dotfiles state=link
    - name: clone dotfiles.secret
      git:
        repo: git@github.com:ryanhanks-wf/dotfiles.secret
        dest: ~/src/github.com/ryanhanks-wf/dotfiles.secret
        update: no
    - name: link dotfiles
      file: src=~/src/github.com/ryanhanks-wf/dotfiles dest=~/dotfiles state=link
    - name: create ~/.pip
      file: dest=~/.pip state=directory
    - name: create bam_cache on /Volumes/Data
      file: dest=/Volumes/Data/.bam_cache state=directory
    - name: link bam_cache
      file: src=/Volumes/Data/.bam_cache dest=~/.bam_cache state=link
    - name: create bam_download_cache dir
      file: dest=/Volumes/Data/.pip_download_cache state=directory
    - name: link bam_download_cache
      file: dest=~/.pip/cache src=/Volumes/Data/.pip_download_cache state=link
    - name: create wheelhouse dir
      file: dest=/Volumes/Data/.pip_wheelhouse state=directory
    - name: link bam_download_cache
      file: dest=~/.pip/wheelhouse src=/Volumes/Data/.pip_wheelhouse state=link
    - name: create workspaces on /Volumes/Data
      file: dest=/Volumes/Data/workspaces state=directory
    - name: link workspaces
      file: src=/Volumes/Data/workspaces dest=~/workspaces state=link

    - include: roles/roderik.superlumic-homebrew/tasks/main.yml

    - name: install cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - google-chrome
        - atom
        - vmware-fusion
        - pycharm
        - hipchat
        - google-hangouts
        - hyperswitch

    - name: tap homebrew/versions
      homebrew_tap: tap=homebrew/versions state=present

    # java is a dependency of maven30
    - name: install casks for bigsky
      homebrew_cask: name={{item}} state=present
      with_items:
        - java
        - googleappengine
        - flash-player-debugger
        - ngrok

    - name: install brew packages for bigsky
      homebrew: name={{item}} state=present
      with_items:
        - ant
        - homebrew/versions/maven30
        - homebrew/versions/node010
        - libjpeg
        - freetype

    - name: clone a copy of the bam workspace to test against
      git:
        repo: git@github.com:ryanhanks-wf/bam_workspace
        dest: ~/src/github.com/ryanhanks-wf/bam_workspace
        update: no
